### PR TITLE
Upgraded asn1js to version 2

### PR DESCRIPTION
**Pull request by fotisl**
Upgraded asn1js to version 2. Furthermore, official typings for asn1js have been used. This allows usage of pkijs version 2 too.

### CODE REVIEW

**Comment by rmhrisk** [comment]
OMG

**Comment by fotisl** [comment]
I hope this is an OMG in a good and not bad sense :)

**Comment by fotisl** [comment]
All problems fixed, @rmhrisk you can now merge.

**Comment by fotisl** [comment]
In addition, I believe this closes #33. Issue #34 should also be closed since we moved from typings to @types.

**Pull request merged**
