### PR TITLE
Added support for Apple Root Program and moved fetching inside every format

### PR DESCRIPTION
**Pull request by fotisl**

### CODE REVIEW

**Comment by rmhrisk** [comment]
This looks cool :)

I was talking with @sleevi today and he mentioned there are some gotcha's with processing the Apple list in this way.

@sleevi, if you could explain what to look for that would be great.

**Comment by sleevi** [comment]
@rmhrisk I was mentioning this script - http://opensource.apple.com/source/security_certificates/security_certificates-55052.40.2/CertificateTool/BuildOSXAsset/buildRootKeychain.rb - as the canonical (current) tool version that does the secondary processing, and special cases like http://opensource.apple.com/source/security_certificates/security_certificates-55052.40.2/certificates/allowlist/ or the fact that the root store is dynamically updatable ( http://opensource.apple.com/source/Security/Security-57337.60.2/OTAPKIAssetTool/ )

**Comment by fotisl** [comment]
Thank you @sleevi. I believe that the only difference is that the buildRootKeychain.rb tool does not add the AppleDEVID.cer certificate, which has been fixed at the latest commit. The SystemCACertificates.keychain contains Intermediates and not Root certificates, and the allowlist contains only leaf certificates from blocked Roots. @rmhrisk do you believe those should be added?
As far as the OTA updates are concerned, it is my understanding that the OTAPKIAssetTool will fetch a new version of the keychains generated from the same files we fetch, thus there is no problem with this.

**Comment by sleevi** [comment]
From an offline conversation, the only area of concern was whether CAs which have technically-enforced whitelists for leaf certs should be considered 'trusted' or not. This is similar to the discussions on mozilla.dev.security.policy with respect to CKK_NSS_TRUST attributes expressing additional constraints (e.g. name constraints, CT policies), or the authroot.stl meta-trust flags.

**Comment by rmhrisk** [comment]
Thanks very much @sleevi / @fotisl. Sounds like this may be the "best we can do" where the largest issue is the additional constraints issue, this is not handled awesome across any of the store processing so I think, however not-optimal, will be acceptable. I am accepting this PR.

**Pull request merged**
